### PR TITLE
#94: implement stelem.i1 - stelem.r8 MSIL opcodes + #95 fix numerical conversion of float types

### PR DESCRIPTION
**Pull request by cyborgyn**
A bit of refactoring as well, around the prepare method, to introduce a similar utility function as can be found around the ldelem implementation.

Also fix numerical conversion of float types.

### CODE REVIEW

**Comment by kekyo** [comment]
Thank you send fixing PR, I will reveiew it within 2 or 3 days, plz wait.

**Comment by kekyo** [comment]
@cyborgyn @pengzeshan I added test code for stelem and conv opcodes. Please notify me when verify on your environment.

**Comment by cyborgyn** [comment]
Thank you for the addition! A very nice set of new tests! All green on my side 1492/1492. :) Took a while to run all of them, though... :)

**Comment by kekyo** [comment]
Finally testing now, and will merge detect no problems on any test.

**Pull request merged**
